
language: cpp
sudo: false

before_install:
- sudo add-apt-repository ppa:team-gcc-arm-embedded/pp
- sudo apt-get update -qq

install:
- sudo apt-get install gcc-arm-embedded

script:
  - arm-none-eabi-gcc --version
  - make --version
  - cd OCAMicro/OCAMicro
  - export OCA_HOME=`pwd`
  - cd Src
  - make stm32Release
