
language: cpp
sudo: false

addons:
  apt:
    packages:
      libc6-i386

cache:
  directories:
    - $HOME/gcc-arm-none-eabi

script:
  - cd OCAMicro/OCAMicro
  - SET OCA_HOME=%CD%
  - cd src
  - make stm32Release
  - pushd %OCA_HOME%
