
language: cpp
sudo: false

addons:
  apt:
    packages:
      - libc6-i386
      - gcc-arm-none-eabi

script:
  - arm-none-eabi-gcc --version
  - cd OCAMicro/OCAMicro
  - export OCA_HOME=`pwd`
  - cd Src
  - make stm32Release
